apiVersion: v1
kind: Namespace
metadata:
  name: shlink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink
  namespace: shlink
spec:
  selector:
    matchLabels:
      app: shlink
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: shlink
    spec:
      containers:
        - name: shlink
          image: shlinkio/shlink:stable
          ports:
            - containerPort: 8080
          env:
            - name: DEFAULT_DOMAIN
              value: link.ieeetamu.org
            - name: IS_HTTPS_ENABLED
              value: "true"
            - name: GEOLITE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: shlink-secrets
                  key: geolite-license-key
            - name: DB_DRIVER
              value: mariadb
            - name: DB_NAME
              value: shlink
            - name: DB_USER
              value: shlink
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shlink-secrets
                  key: mariadb-password
            - name: DB_HOST
              value: mariadb.mariadb.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: shlink
  namespace: shlink
spec:
  selector:
    app: shlink
  type: ClusterIP
  ports:
    - name: http
      port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shlink
  namespace: shlink
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`link.ieeetamu.org`)
      kind: Rule
      services:
        - name: shlink
          port: 8080
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: shlink
  namespace: shlink
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  cleanupPolicy: Skip # keep the database when deleting this resource
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: shlink
  namespace: shlink
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: shlink-secrets
    key: mariadb-password
  # This field defaults to 10
  maxUserConnections: 20
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: shlink
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: shlink
  table: "*"
  username: shlink
  grantOption: true
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shlink-dashboard
  namespace: shlink
spec:
  selector:
    matchLabels:
      app: shlink-dashboard
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: shlink-dashboard
    spec:
      containers:
        - name: shlink-dashboard
          image: shlinkio/shlink-web-client
          ports:
            - containerPort: 8080
          env:
            - name: SHLINK_SERVER_URL
              value: https://link.ieeetamu.org
            - name: SHLINK_SERVER_NAME
              value: IEEE-TAMU
            - name: SHLINK_SERVER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shlink-secrets
                  key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: shlink-dashboard
  namespace: shlink
spec:
  selector:
    app: shlink-dashboard
  type: ClusterIP
  ports:
    - name: http
      port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shlink-dashboard
  namespace: shlink
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`link-admin.ieeetamu.org`)
      kind: Rule
      services:
        - name: shlink-dashboard
          port: 8080
      middlewares:
        - name: shlink-dashboard-auth
          namespace: shlink
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: shlink-dashboard-auth
  namespace: shlink
spec:
  basicAuth:
    secret: shlink-dashboard-basic-auth
