apiVersion: v1
kind: Secret
metadata:
  name: traefik-basic-auth
  namespace: kube-system
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:NKE/BcdsEFD7Hg==,iv:yKiMkRnJJqogDvKID2IQNI7TJJni6kKeXR3Xugmx5A4=,tag:EZK4/G2H7ClFC6SUgDZ0/w==,type:str]
  password: ENC[AES256_GCM,data:IzDTdecRHhXAPrXZ7EeRD6VW1iNG0g==,iv:+jkWv98ySd4Skq2/yiFrh4voknFvJj3j9+7jbwmnMsg=,tag:nwylcAFpTBNlSwRWrO19Zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-02-02T18:52:44Z"
  mac: ENC[AES256_GCM,data:6fKi1UEYd9uje6p41Zsk35TSfOY+B5Rt56C6oW63ExA0K6ksvQryXiVB5pUE8gOBTLTibrNz0mqmYlj4uA43O3zdDCTZFX7EHQDAGLkeAMxS9A0dWD3LvDCGEiKwg95wAgy13m4yfKcI/kjquMNEO7knLvoed6YQrXkZ2gNZDtE=,iv:IJV+JcbsJLn2L5PJeqXhN7JxhT+ZKJuALGVK0HYUcoo=,tag:2R09zA6aSdWXV3PiazBWlw==,type:str]
  pgp:
    - created_at: "2025-02-02T18:51:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMAwAAAAAAAAAAAQ/9EATZwA0iABRYlIkcfDmHKPtF++Hnhu6JbAOlM64AeXbC
        MIdERIUmTgO6tOlq2pCC/dRs7rxdbSn/zYnnugWBXrh7NXREF3VQk9Hc2yflHePB
        G86yUBu9SkXU5z0YxsejyLgKVNUJySkYJLrG2sltkr+qdWIqveDNEaQlZ36koBvK
        85sq31a7hpnPb4dQvG4mfNRr5HqTyFsg3uu2ZqZhQHUC2hC+emTtdE1WQp/SX0RZ
        H9slIOnf+Yqq9mVPJYVV5SkdxpD1sMzHggFvWKznn6Ie5f6j7862jz5MC9z4vlwg
        tgFfRZBCyGtU4Iu2f4s/9vfkD+RnXzpP7tO4kORBNcmOjDNJBLnfuxKAcB5WueDj
        yqNdfLjn12KpuFaJuTKXvKyqEuIW8+oAiE3IoGH3xtG+txEUUZBeyUjHwss6WjGV
        +qKuY4AQ3l34dm2MJoi3q7d1hlrBbrOmX2COLQCT3vhD7ITCUZtGqtqq0vWgZwml
        8lQOji4OEL+7kHiW3V8yezUiJqIKturRaeJ+eQvd6+8QTMXAjdCKcZw3i4kvcpYo
        muUrD4TkZ+6m5iFPm5XlBl6TV9jL/AYbAgMVWrqPgPbbEEvIxZx0tH1dlEEwuFrW
        y7/GyYU9SE2h1hUmGiOy31XaHZ45yfxfhmpHm6uzrHKUQCrHjY+S84Ku0AscSG/U
        aAEJAhB/lGMyARsxcjKrWj3lMgEK0GhFck9kUFSwPlRjfdNksyiYiQrZr7sZJVbb
        NM/ySf1b29f/jTAuuv+RnSN8ZvgfBAldZZuYp5EMc7lalZPBw92Mb9cryHqLKESt
        KV+baJLvf+tB
        =CYDY
        -----END PGP MESSAGE-----
      fp: 483A112B3567C4F0DF8974E1D776F5702D7E83AB
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
