apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: mariadb
  image: mariadb:latest
  port: 3306
  storage:
    size: 1Gi
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
      # metrics:
      #   enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb
  # davfs2 user
  securityContext:
    runAsUser: 101
    runAsGroup: 101
  serviceAccountName: backup
  compression: gzip
  storage:
    persistentVolumeClaim:
      storageClassName: backup-webdav
      resources:
        requests:
          storage: 1Gi
      accessModes:
        - ReadWriteOnce
  args:
    - --single-transaction
    - --all-databases
    - --verbose
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  affinity:
    antiAffinityEnabled: true
