apiVersion: v1
kind: Namespace
metadata:
  name: backups
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-webdav
  namespace: backups
provisioner: webdav.csi.io
parameters:
  share: https://u349919-sub1.your-storagebox.de
  csi.storage.k8s.io/provisioner-secret-name: backupcreds
  csi.storage.k8s.io/provisioner-secret-namespace: backups
  csi.storage.k8s.io/node-publish-secret-name: backupcreds
  csi.storage.k8s.io/node-publish-secret-namespace: backups
reclaimPolicy: Retain # keep everything since this storage is used for backups
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=101
  - gid=101
