apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-webdav
  namespace: backups
  labels:
    app: backup-test
spec:
  serviceName: statefulset-webdav
  replicas: 1
  template:
    metadata:
      labels:
        app: backup-test
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-webdav
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/webdav/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/webdav
              readOnly: false
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backup-test
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        storageClassName: backup-webdav
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
