apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  DB_NAME: vaultwarden
  DB_PORT: "3306"
  DB_HOST: mariadb.mariadb.svc.cluster.local
  DB_USER: vaultwarden
  # SIGNUPS_ALLOWED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  replicas: 1
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: vaultwarden-config
            - secretRef:
                name: vaultwarden-secrets
          env:
            - name: DATABASE_URL
              value: mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden
  type: ClusterIP
  ports:
    - name: http
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.ieeetamu.org`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  cleanupPolicy: Skip # keep the database when deleting this resource
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  passwordSecretKeyRef:
    name: vaultwarden-secrets
    key: DB_PASSWORD
  maxUserConnections: 20
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: vaultwarden
spec:
  mariaDbRef:
    name: mariadb
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: vaultwarden
  table: "*"
  username: vaultwarden
  grantOption: true
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
